name: honeydew
version: 0.0.1
environment:
  sdk: '>=2.0.0-dev.44.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+10
  angular_router: ^2.0.0-alpha+10
  yaml: ^2.1.13

dev_dependencies:
  angular_test: ^2.0.0-alpha+8
  build_runner: ^0.8.2+2
  build_web_compilers: ^0.3.6
  sass_builder: ^1.2.0
