name: honeydew
version: 0.0.1
# sdk: '>=2.0.0'

dependencies:
  angular: '^5.0.0-alpha+6'

dev_dependencies:
  angular_test: ^2.0.0-alpha+4
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.3
  test: ^0.12.31

dependency_overrides:
  analyzer: ^0.31.2-alpha.0

transformers:
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart

- test/pub_serve:
    $include: test/**_test.dart

- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc