name: honeydew
version: 0.0.2
environment:
  sdk: '^2.0.0'

dependencies:
  angular: ^5.0.0
  angular_router: ^2.0.0-alpha+19
  yaml: ^2.1.15
  uuid: ^1.0.3

dev_dependencies:
  test: ^1.3.0
  angular_test: ^2.0.0
  build_runner: ^0.10.1+1
  build_web_compilers: ^0.4.3
  sass_builder: ^2.1.1
