name: honeydew
version: 0.0.1
environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+7
  angular_router: ^2.0.0-alpha+7
  yaml: ^2.1.13

dev_dependencies:
  angular_test: ^2.0.0-alpha+5
  build_runner: ^0.7.13+1
  build_web_compilers: ^0.3.3
  sass_builder: ^1.1.4